### ISSUE TITLE
Linking your Containers

### ISSUE THREAD

**Issue by zachariahyoung** [cer/microservices-examples#2]
Thanks for doing this sample project.  I have been able to pull a few items from this project.  

Wondering if you had considered linking your mongo and rabbitmq containers to your webservice.  I was able to setup and hoping to share what I figured out.

Basically when you link to another container new environment variables are created with ip and port information in the new container.

With this information set you can define them in the application.properties files.

      spring.data.mongodb.host = ${MONGODB_PORT_27017_TCP_ADDR:127.0.0.1}

This is the repo I have this setup in for reference.  Hope this helps

https://github.com/zachariahyoung/docker-rest

**Comment by cer** [comment]
The configuration now relies on linking creating an entry in /etc/hosts for mongodb so it can be referenced via mongodb://*mongodb*/userregistration
