### ISSUE TITLE
web.environment.EUREKA_INSTANCE_PREFER_IP_ADDRESS contains true, which is an invalid type, it should be a string, number, or a null

### ISSUE THREAD

**Issue by xtaje** [cer/microservices-examples#7]
docker-compose pull gives me the following error:

ERROR: Validation failed in file './docker-compose.yml', reason(s):
web.environment.EUREKA_INSTANCE_PREFER_IP_ADDRESS contains true, which is an invalid type, it should be a string, number, or a null

changing true to 1 fixes it.

**Comment by cer** [comment]
Fixed with the latest commit

**Comment by dimboyNew** [comment]
thanks, i commented it, so it won't affect ,right? 
if possible,hope you can be so kind that guide some junior java developer to approach micro-services with docker and spring booter.
Feel free to suggest any website , documentations, books :+1: dimboynew@gmail.com,except all your blogs.

dim
